---
title: "genetic_association_analysis_case_control"
author: "Ruixi Li"
date: "2024-02-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# STATISTICAL BACKGROUND-CATEGORICAL DATA ANALYSIS

```{r three_test}

# load the data
gc <- c(10,190, 800, 3, 100, 900)
ac <- c(2*gc[1]+gc[2], gc[2]+2*gc[3], 2*gc[4]+gc[5], gc[5]+2*gc[6]) 
gc1 <- c(gc[1]+gc[2],gc[3], gc[4]+gc[5], gc[6]) 
gc2 <- c(gc[1], gc[2]+gc[3], gc[4], gc[5]+gc[6])

# chi-square test
pvg <- chisq.test(matrix(gc,ncol=3, byrow=T), corr=FALSE)$p.value 
pva <- chisq.test(matrix(ac,ncol=2, byrow=T), corr=FALSE)$p.value 
pvg1<-chisq.test(matrix(gc1,ncol=2, byrow=T), corr=FALSE)$p.value 
pvg2<-chisq.test(matrix(gc2, ncol=2, byrow=T),corr=FALSE)$p.value 
pvb <- min(pvg1,pvg2)

print(c(pvg,pva,pvb)) # 6.918239e-09 9.150309e-10 1.224003e-09 

# fisher's exact test
pvg.f <- fisher.test(matrix(gc,ncol=3,byrow=T))$p.value 
pva.f <- fisher.test(matrix(ac,ncol=2,byrow=T))$p.value 
pvg1.f <- fisher.test(matrix(gc1,ncol=2,byrow=T))$p.value 
pvg2.f <- fisher.test(matrix(gc2,ncol=2,byrow=T))$p.value 
pvb.f <- min(pvg1.f,pvg2.f)
print(c(pvg.f,pva.f,pvb.f))# 2.412721e-09 8.047005e-10 1.132535e-09

# Cochran-Armitage trend test
pvcat <- prop.trend.test(gc[1:3], gc[1:3]+gc[4:6], score=c(0, 0.5, 1))$p.value 
print(c(pvcat)) # 9.820062e-10

# explore the effect of sample size
gc <- gc*2
...	# repeat the tests	
print(c(pvg, pva, pvb))	# 4.786203e-17 4.716312e-18 8.379499e-18	
print(c(pvg.f, pva.f,pvb.f))# 1.231881e-17 3.485271e-18 6.810263e-18 
print(c(pvcat))# 5.422705e-18
```



```{r OR_95%CI}
# define a function calculating OR and its 95% CI based on counts(in frequency tables) and alpha
ci.or <- function(counts,alpha){	# alpha=0.05 corresponds to 95%CI	
f <- qnorm(1- alpha/2)	# if alpha=0.05，f=1.96	
or <- counts[1]*counts[4]/(counts[2]*counts[3])
sq <- sqrt(1/counts[1]+1/counts [2]+1/counts [3]+1/counts [4]) 
upper <- exp( log(or) + f*sq) 
lower <- exp( log(or) - f*sq) 
res <- c(lower,or,upper) 
res
}

# explore the effect of sample size and alpha toward the 95%CI
print(ci.or(ac,0.05))	# 1.650411 2.102878 2.679390	
print(ci.or(ac,0.01))	# 1.529428 2.102878 2.891339	
ac <- ac*2	# double the sample size	
print(ci.or(ac,0.05))	# 1.771784 2.102878 2.495842	
print(ci.or(ac,0.01))	# 1.678927 2.102878 2.633882

```

# DISEASE GENE MUTATION IS NOT DIRECTLY OBSERVABLE IN GENETIC ANALYSES

```{r}
# estimating haplotype frequency
g<- c(14, 0, 0, 34, 4, 0, 109, 50, 10) 
n1 <- g[5]/2 
n2 <- g[5]/2 
N <- 2*sum(g)
delta <- 1
f<- c(0.25, 0.25, 0.25, 0.25)

while( delta > 1e-10){ 
  fold <- f
  f <- c(2*g[1]+g[2]+g [4]+n1,2*g[3]+g[2]+g[6]+n2, 2*g[7]+g[4]+g[8]+n2, 2*g[9]+g [6]+g[8]+n1)/N 
  n1 <- g[5]*f[1]*f[4]/(f[1] *f [4] +f[2]*f[3]) 
  n2 <- g[5]*f[2]*f [3]/(f[1]*f [4]+f [2]*f[3]) 
  delta <- sum(abs(f-fold))
  print(round(f,4)) # 0.1448 0.0045 0.6878 0.1629
                    # 0.1483 0.00110.6843 0.1664
                    # 0.1491 0.00030.6835 0.1672
                    # 0.1493 0.00010.6833 0.1674
                    # 0.1493 0.0000 0.6833 0.1674
}
```

